version: '3'
services:
  mockserver:
    image: "nighteblis/hissummer-mockserver:latest"
    ports:
      - "8080:8080"
    environment:
     mongodbHost: mongodb
     serverPort: 8080
     mongodbPort: 27017
    links:
      - mongodb

  mongodb:
    image: "mongo:4.2.5-bionic"
